Refactored methods and classes
Kenneth-CSU/ITC_205_A2 pull request #5
Opened 2019-08-14 04:02 UTC by RevinTownsend

Fixing conflicts

2019-08-14 04:37 UTC, Kenneth-CSU requested changes

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public loan IssueLoan(book book, member member) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public loan LoanByBookID(int bookId) {
C/M?

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookControl.java
>  	public void Swiped(int MEMMER_ID) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookControl.java
>  	public void Scanned(int bookId) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookControl.java
>  	public void Complete() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookControl.java
> +	public void CommitLoans() {
method?

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookControl.java
> +	public void Cancel() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookUI.java
>  	public BorrowBookUI(BorrowBookControl control) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookUI.java
> +	private String Input(String prompt) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookUI.java
> +	private void Output(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookUI.java
> +	public void SetState(UIState STATE) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/BorrowBookUI.java
> +	public void Run() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Calendar.java
> +	public void IncrementDate(int days) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Calendar.java
> +	public synchronized void SetDate(Date date) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Calendar.java
> +	public synchronized Date DueDate(int loanPeriod) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Calendar.java
> +	public synchronized long GetDaysDifference(Date targetDate) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
> +	private ControlState StAtE;
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
>  	public FixBookControl() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
> +	public void SetUI(FixBookUI ui) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
> +	public void BookScanned(int bookId) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
> +	public void FixBook(boolean MUST_fix) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookControl.java
> +	public void ScanningComplete() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookUI.java
> +	public void SetState(UIState state) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookUI.java
> +	public void SetState(UIState state) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookUI.java
> +	private void Output(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/FixBookUI.java
> +	public void Display(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void CurrentLoans() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void Books() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void Members() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void BorrowBook() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void ReturnBook() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void FixBooks() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void IncrementDate() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void AddBook() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void AddMember() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static String Input(String prompt) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/Main.java
> +	private static void Output(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineControl.java
> +	public void SetUI(PayFineUI ui) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineControl.java
> +	public void CardSwiped(int memberId) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineControl.java
> +	public void Cancel() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineControl.java
> +	public double PayFine(double AmOuNt) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineUI.java
> +	public void SetState(UI_STATE state) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineUI.java
> +	public void Run() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineUI.java
> +	private String Input(String prompt) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineUI.java
> +	private void Output(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/PayFineUI.java
> +	public void Display(Object object) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/ReturnBookControl.java
> +	public void SetUI(ReturnBookUI ui) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/ReturnBookControl.java
> +	public void BookScanned(int Book_ID) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/ReturnBookControl.java
> +	public void ScanningComplete() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/ReturnBookControl.java
> +	public void DischargeLoan(boolean isDamaged) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/ReturnBookUI.java
> +	public void Run() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/book.java
> +	public Book(String author, String title, String callNo, int id) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/book.java
> +	public String Title() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/book.java
>  	public void Repair() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	private Library() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public List<member> Members() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public List<book> Books() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public member AddMem(String lastName, String firstName, String email, int phoneNo) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public book AddBook(String a, String t, String c) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public member Member(int memberId) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public int LoanLimit() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public boolean MemberCanBorrow(member member) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public int LoansRemainingForMember(member member) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public double CalculateOverdueFine(loan loan) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public void DischargeLoan(loan currentLoan, boolean isDamaged) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public void CheckCurrentLoans() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/library.java
> +	public void RepairBook(book currentBook) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/loan.java
> +	public Loan(int loanId, Book book, Member member, Date dueDate) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/loan.java
> +	public void CheckOverdue() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/loan.java
> +	public boolean Overdue() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/loan.java
> +	public Date GetDueDate() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/loan.java
> +	public void Discharge() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public Member(String lastName, String firstName, String email, int phoneNo, int id) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public int GetID() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public List<loan> GetLoans() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public int NumberOfCurrentLoans() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public double FinesOwed() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public void TakeOutLoan(loan loan) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public String GetLastName() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public String GetFirstName() {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public void AddFine(double fine) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public double PayFine(double AmOuNt) {
method

2019-08-14 04:37 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public void DischargeLoan(loan LoAn) {
method

2019-08-15 00:26 UTC, RevinTownsend reviewed
Reviews / changes checked and approved

2019-08-15 01:02 UTC, RevinTownsend commented
Changes approved

2019-08-15 01:02 UTC, closed without merging

2019-08-16 07:06 UTC, Kenneth-CSU commented on ITC205_201960_Asg2_Baseline_Code/member.java
> +	public void DischargeLoan(loan LoAn) {
DischargeLoan should be dischargeLoan